### ISSUE TITLE
540 Connectivity Disrupted after deploying

### ISSUE THREAD

**Issue by stoopman** [akamai/eaa-k8s-connector#5]
I can successfully deploy this workload to k8s (on AKS), through helm or the separate StatefulSet.yaml (kubectl apply)

After deploying, the connector gets approved and finally the status is ✅  in EAA portal. However, when connecting this connector to a simple application I get the error
> **540 Connectivity Disrupted**
> (akamai/nginx)
> Info: Connectivity with Enterprise Cloudlet broken
> Id: xxx

The authentication with the IDP works fine, but trying to reach the origin server after that does not. 

Additional info:
- Kubernetes 1.25.6
- Ubuntu 22.04
- Latest version of this repo
- Seems like it used to work a while ago, maybe the internal akamai connector image has been updated.

Hope someone can help

**Comment by MikeSchiessl** [comment]
Hey @stoopman , 
are you trying to run a "HTTP" app against this connector ?  (I assume, otherwise the app assignment should throw an error ;) )

Can you please enable debugging on the connector and verify (curl), the connector is able to see the app within the k8s ecosystem? 

feel free to reach out to me via Email - so we can share related details w/o the public ;)
mschiess@akamai.com


Best regards
Mike
